### ISSUE TITLE
DevBuilds crashing browser

### ISSUE THREAD

**Issue by FuJa0815** [Revolutionary-Games/ThriveDevCenter#90]
There seems to be some kind of infinite loop in the DevBuilds tab. Firefox complains about the website "slowing down your browser" and I can't interact with the page (usually indicating a loop). After about a minute or so it stops by itself (maybe firefox stops a script?)
Trail of the JS-Console:
![grafik](https://user-images.githubusercontent.com/30809803/115995882-522d7b80-a5dd-11eb-8a34-769c62f2710f.png)

**Comment by hhyyrylainen** [comment]
I know about this problem. For me in firefox it takes about 30 seconds to load the devbuilds page (but it doesn't complain, I probably have a faster CPU so it doesn't hit the timeout).
I've started to rewrite the entire site from scratch to get around this problem as the previous technology (hyperstack) is too difficult to use and doesn't seem to get updates.

https://github.com/Revolutionary-Games/ThriveDevCenter/tree/blazor
